const app = Vue.createApp({
    data() {
      return {
        message: "Hello Vue.js",
        categories: [
          { id: 1, title: "Smartfonlar", link: "./images/image 6.svg" },
          {
            id: 2,
            title: "Kompyuter va noutbuklar",
            link: "./images/image 6 (1).svg",
          },
          { id: 3, title: "Televizorlar", link: "./images/image 6 (2).svg" },
          { id: 4, title: "Aqlli soatlar", link: "./images/image 6 (3).svg" },
          { id: 5, title: "Quloqchinlar", link: "./images/image 6 (4).svg" },
          { id: 6, title: "Konditsionerlar", link: "./images/image 6 (5).svg" },
          { id: 7, title: "Sovutkichlar", link: "./images/image 6 (6).svg" },
          {
            id: 8,
            title: "Kir yuvish mashinalari",
            link: "./images/image 6 (7).svg",
          },
        ],
        soldOuts: [
          {
            id: 1,
            yangilik: false,
            topsale: false,
            price: "299 000 so'm",
            title: "Apple Airpods Pro simsiz quloqchin , Oq rangda",
            orders: "1230 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 2,
            yangilik: false,
            topsale: true,
            price: "16 114 285 so'm",
            title:
              "Apple Mackbook Pro 13 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB",
            orders: "230 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 3,
            yangilik: true,
            topsale: false,
            price: "4 234 00 so'm",
            title: "Apple watch 4",
            orders: "543 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 4,
            yangilik: false,
            topsale: false,
            price: "1 340 00 so'm",
            title: "Robot - tozalagich Xiaomi Mi Robot",
            orders: "876 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 5,
            yangilik: true,
            topsale: false,
            price: "1 345 00 so'm",
            title: "Oynali Fotoaparat Canon EOS 6D Body",
            orders: "565 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 6,
            yangilik: false,
            topsale: false,
            price: "299 000 so'm",
            title: "Apple Airpods Pro simsiz quloqchin , Oq rangda",
            orders: "1230 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 7,
            yangilik: true,
            topsale: false,
            price: "16 114 285 so'm",
            title:
              "Apple Mackbook Pro 13 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB",
            orders: "230 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 8,
            yangilik: false,
            topsale: false,
            price: "4 234 00 so'm",
            title: "Apple watch 4",
            orders: "543 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 9,
            yangilik: false,
            topsale: true,
            price: "1 340 00 so'm",
            title: "Robot - tozalagich Xiaomi Mi Robot",
            orders: "876 ta buyurtma",
            link: "./images/image 15.svg",
          },
          {
            id: 10,
            yangilik: false,
            topsale: false,
            price: "1 345 00 so'm",
            title: "Oynali Fotoaparat Canon EOS 6D Body",
            orders: "565 ta buyurtma",
            link: "./images/image 15.svg",
          },
        ],
        brands: [
          { id: 1, link: "./images/image.svg" },
          { id: 2, link: "./images/image (1).svg" },
          { id: 3, link: "./images/image (2).svg" },
          { id: 4, link: "./images/image (3).svg" },
          { id: 5, link: "./images/image (4).svg" },
          { id: 6, link: "./images/image (5).svg" },
          { id: 7, link: "./images/image (6).svg" },
          { id: 8, link: "./images/image (7).svg" },
          { id: 9, link: "./images/image (8).svg" },
          { id: 10, link: "./images/image (8).svg" },
          { id: 11, link: "./images/image (8).svg" },
          { id: 12, link: "./images/image (8).svg" },
          { id: 13, link: "./images/image (8).svg" },
          { id: 14, link: "./images/image (8).svg" },
          { id: 15, link: "./images/image (8).svg" },
        ],
        markets: [
          { id: 1, link: "./images/image (9).svg" },
          { id: 1, link: "./images/image (10).svg" },
          { id: 1, link: "./images/image (11).svg" },
          { id: 1, link: "./images/image (12).svg" },
          { id: 1, link: "./images/image (13).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
          { id: 1, link: "./images/image (8).svg" },
        ],
      };
    },
    methods: {},
    mounted() {},
  });
  
  app.mount("#root");